[
  {
    "package": {
      "name": "pyjwt",
      "version": "2.10.0",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "dstack-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-12-02T18:57:24Z",
        "published": "2024-12-02T18:34:11Z",
        "schema_version": "1.6.0",
        "id": "GHSA-75c5-xw7c-p5pm",
        "aliases": [
          "CVE-2024-53861"
        ],
        "summary": "PyJWT Issuer field partial matches allowed",
        "details": "### Summary\nThe wrong string if check is run for `iss` checking, resulting in `\"acb\"` being accepted for `\"_abc_\"`.\n\n### Details\nThis is a bug introduced in version [2.10.0](https://github.com/jpadilla/pyjwt/commit/1570e708672aa9036bc772476beae8bfa48f4131#diff-6893ad4a1c5a36b8af3028db8c8bc3b62418149843fc382faf901eaab008e380R366): checking the \"iss\" claim\nchanged from `isinstance(issuer, list)` to `isinstance(issuer,\nSequence)`.\n\n```diff\n-        if isinstance(issuer, list):\n+        if isinstance(issuer, Sequence):\n            if payload[\"iss\"] not in issuer:\n                raise InvalidIssuerError(\"Invalid issuer\")\n        else:\n```\n\nSince str is a Sequnce, but not a list, `in` is also used for string\ncomparison. This results in `if \"abc\" not in \"__abcd__\":` being\nchecked instead of `if \"abc\" != \"__abc__\":`.\n### PoC\nCheck out the unit tests added here: https://github.com/jpadilla/pyjwt-ghsa-75c5-xw7c-p5pm\n```python\n        issuer = \"urn:expected\"\n\n        payload = {\"iss\": \"urn:\"}\n\n        token = jwt.encode(payload, \"secret\")\n\n        # decode() succeeds, even though `\"urn:\" != \"urn:expected\". No exception is raised.\n        with pytest.raises(InvalidIssuerError):\n            jwt.decode(token, \"secret\", issuer=issuer, algorithms=[\"HS256\"])\n```\n\n\n### Impact\n\nI would say the real world impact is not that high, seeing as the signature still has to match. We should still fix it.\n",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "pyjwt",
              "purl": "pkg:pypi/pyjwt"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "2.10.0"
                  },
                  {
                    "fixed": "2.10.1"
                  }
                ]
              }
            ],
            "versions": [
              "2.10.0"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/12/GHSA-75c5-xw7c-p5pm/GHSA-75c5-xw7c-p5pm.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:N/I:L/A:N"
          },
          {
            "type": "CVSS_V4",
            "score": "CVSS:4.0/AV:N/AC:L/AT:P/PR:H/UI:N/VC:N/VI:L/VA:N/SC:N/SI:N/SA:N"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/jpadilla/pyjwt/security/advisories/GHSA-75c5-xw7c-p5pm"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-53861"
          },
          {
            "type": "WEB",
            "url": "https://github.com/jpadilla/pyjwt/commit/1570e708672aa9036bc772476beae8bfa48f4131#diff-6893ad4a1c5a36b8af3028db8c8bc3b62418149843fc382faf901eaab008e380R366"
          },
          {
            "type": "WEB",
            "url": "https://github.com/jpadilla/pyjwt/commit/33022c25525c1020869c71ce2a4109e44ae4ced1"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/jpadilla/pyjwt"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-697"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2024-12-02T18:34:11Z",
          "nvd_published_at": "2024-11-29T19:15:09Z",
          "severity": "LOW"
        }
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-75c5-xw7c-p5pm"
        ],
        "aliases": [
          "CVE-2024-53861",
          "GHSA-75c5-xw7c-p5pm"
        ],
        "max_severity": "2.2"
      }
    ]
  },
  {
    "package": {
      "name": "python-multipart",
      "version": "0.0.17",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "dstack-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-12-02T22:12:17Z",
        "published": "2024-12-02T21:37:04Z",
        "schema_version": "1.6.0",
        "id": "GHSA-59g5-xgcq-4qw3",
        "aliases": [
          "CVE-2024-53981"
        ],
        "summary": "Denial of service (DoS) via deformation `multipart/form-data` boundary",
        "details": "### Summary\n\nWhen parsing form data, `python-multipart` skips line breaks (CR `\\r` or LF `\\n`) in front of the first boundary and any tailing bytes after the last boundary. This happens one byte at a time and emits a log event each time, which may cause excessive logging for certain inputs.\n\nAn attacker could abuse this by sending a malicious request with lots of data before the first or after the last boundary, causing high CPU load and stalling the processing thread for a significant amount of time. In case of ASGI application, this could stall the event loop and prevent other requests from being processed, resulting in a denial of service (DoS).\n\n### Impact\n\nApplications that use `python-multipart` to parse form data (or use frameworks that do so) are affected. \n\n### Original Report\n\nThis security issue was reported by:\n- GitHub security advisory in Starlette on October 30 by @Startr4ck\n- Email to `python-multipart` maintainer on October 3 by @mnqazi",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "python-multipart",
              "purl": "pkg:pypi/python-multipart"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "0.0.18"
                  }
                ]
              }
            ],
            "versions": [
              "0.0.1",
              "0.0.10",
              "0.0.11",
              "0.0.12",
              "0.0.13",
              "0.0.14",
              "0.0.15",
              "0.0.16",
              "0.0.17",
              "0.0.2",
              "0.0.3",
              "0.0.4",
              "0.0.5",
              "0.0.6",
              "0.0.7",
              "0.0.8",
              "0.0.9"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/12/GHSA-59g5-xgcq-4qw3/GHSA-59g5-xgcq-4qw3.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
          },
          {
            "type": "CVSS_V4",
            "score": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/Kludex/python-multipart/security/advisories/GHSA-59g5-xgcq-4qw3"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-53981"
          },
          {
            "type": "WEB",
            "url": "https://github.com/Kludex/python-multipart/commit/c4fe4d3cebc08c660e57dd709af1ffa7059b3177"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/Kludex/python-multipart"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-770"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2024-12-02T21:37:04Z",
          "nvd_published_at": "2024-12-02T16:15:14Z",
          "severity": "HIGH"
        }
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-59g5-xgcq-4qw3"
        ],
        "aliases": [
          "CVE-2024-53981",
          "GHSA-59g5-xgcq-4qw3"
        ],
        "max_severity": "8.7"
      }
    ]
  }
]