[
  {
    "package": {
      "name": "configobj",
      "version": "5.0.8",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "mycli-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-02-18T05:29:13Z",
        "published": "2023-04-03T06:30:19Z",
        "schema_version": "1.6.0",
        "id": "GHSA-c33w-24p9-8m24",
        "aliases": [
          "CVE-2023-26112"
        ],
        "summary": "configobj ReDoS exploitable by developer using values in a server-side configuration file",
        "details": "All versions of the package configobj are vulnerable to Regular Expression Denial of Service (ReDoS) via the validate function, using (.+?)\\((.*)\\). **Note:** This is only exploitable in the case of a developer, putting the offending value in a server side configuration file.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "configobj",
              "purl": "pkg:pypi/configobj"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "last_affected": "5.0.8"
                  }
                ]
              }
            ],
            "versions": [
              "4.4.0",
              "4.5.0",
              "4.5.1",
              "4.5.2",
              "4.5.3",
              "4.6.0",
              "4.7.0",
              "4.7.1",
              "4.7.2",
              "5.0.0",
              "5.0.1",
              "5.0.2",
              "5.0.3",
              "5.0.4",
              "5.0.5",
              "5.0.6",
              "5.0.7",
              "5.0.8"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/04/GHSA-c33w-24p9-8m24/GHSA-c33w-24p9-8m24.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L"
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-26112"
          },
          {
            "type": "WEB",
            "url": "https://github.com/DiffSK/configobj/issues/232"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/DiffSK/configobj"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BO4RLMYEJODCNUE3DJIIUUFVTPAG6VN"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NZHY7B33EFY4LESP2NI4APQUPRROTAZK"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PYU4IHVLOTYMFPH7KDOJGKZQR4GKWPFK"
          },
          {
            "type": "WEB",
            "url": "https://security.snyk.io/vuln/SNYK-PYTHON-CONFIGOBJ-3252494"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-1333"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-04-04T21:40:45Z",
          "nvd_published_at": "2023-04-03T05:15:00Z",
          "severity": "LOW"
        }
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-c33w-24p9-8m24"
        ],
        "aliases": [
          "CVE-2023-26112",
          "GHSA-c33w-24p9-8m24"
        ],
        "max_severity": "3.7"
      }
    ]
  },
  {
    "package": {
      "name": "pymysql",
      "version": "1.1.0",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "mycli-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-05-21T19:41:47Z",
        "published": "2024-05-21T18:31:23Z",
        "schema_version": "1.6.0",
        "id": "GHSA-v9hf-5j83-6xpp",
        "aliases": [
          "CVE-2024-36039"
        ],
        "summary": "PyMySQL SQL Injection vulnerability",
        "details": "PyMySQL through 1.1.0 allows SQL injection if used with untrusted JSON input because keys are not escaped by `escape_dict`.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "pymysql",
              "purl": "pkg:pypi/pymysql"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "1.1.1"
                  }
                ]
              }
            ],
            "versions": [
              "0.10.0",
              "0.10.1",
              "0.2",
              "0.3",
              "0.4",
              "0.5",
              "0.6",
              "0.6.1",
              "0.6.2",
              "0.6.2-rc1",
              "0.6.3",
              "0.6.4",
              "0.6.4.dev1",
              "0.6.5",
              "0.6.6",
              "0.6.7",
              "0.7.0",
              "0.7.1",
              "0.7.10",
              "0.7.11",
              "0.7.2",
              "0.7.3",
              "0.7.4",
              "0.7.5",
              "0.7.6",
              "0.7.7",
              "0.7.8",
              "0.7.9",
              "0.8.0",
              "0.8.1",
              "0.9.0",
              "0.9.1",
              "0.9.2",
              "0.9.3",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "1.0.3",
              "1.0.3rc1",
              "1.1.0",
              "1.1.0rc1",
              "1.1.0rc2"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/05/GHSA-v9hf-5j83-6xpp/GHSA-v9hf-5j83-6xpp.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-36039"
          },
          {
            "type": "WEB",
            "url": "https://github.com/PyMySQL/PyMySQL/commit/521e40050cb386a499f68f483fefd144c493053c"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/PyMySQL/PyMySQL"
          },
          {
            "type": "WEB",
            "url": "https://github.com/PyMySQL/PyMySQL/releases/tag/v1.1.1"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-89"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2024-05-21T19:23:15Z",
          "nvd_published_at": "2024-05-21T16:15:26Z",
          "severity": "CRITICAL"
        }
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-v9hf-5j83-6xpp"
        ],
        "aliases": [
          "CVE-2024-36039",
          "GHSA-v9hf-5j83-6xpp"
        ],
        "max_severity": "9.8"
      }
    ]
  },
  {
    "package": {
      "name": "sqlparse",
      "version": "0.4.4",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "mycli-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-05-01T11:15:56Z",
        "published": "2024-04-15T20:21:25Z",
        "schema_version": "1.6.0",
        "id": "GHSA-2m57-hf25-phgg",
        "aliases": [
          "CVE-2024-4340"
        ],
        "summary": "sqlparse parsing heavily nested list leads to Denial of Service",
        "details": "### Summary\nPassing a heavily nested list to sqlparse.parse() leads to a Denial of Service due to RecursionError.\n\n### Details + PoC\nRunning the following code will raise Maximum recursion limit exceeded exception:\n```py\nimport sqlparse\nsqlparse.parse('[' * 10000 + ']' * 10000)\n```\nWe expect a traceback of RecursionError:\n```py\nTraceback (most recent call last):\n  File \"trigger_sqlparse_nested_list.py\", line 3, in <module>\n    sqlparse.parse('[' * 10000 + ']' * 10000)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/__init__.py\", line 30, in parse\n    return tuple(parsestream(sql, encoding))\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/filter_stack.py\", line 36, in run\n    stmt = grouping.group(stmt)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/grouping.py\", line 428, in group\n    func(stmt)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/grouping.py\", line 53, in group_brackets\n    _group_matching(tlist, sql.SquareBrackets)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/grouping.py\", line 48, in _group_matching\n    tlist.group_tokens(cls, open_idx, close_idx)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 328, in group_tokens\n    grp = grp_cls(subtokens)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 161, in __init__\n    super().__init__(None, str(self))\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 165, in __str__\n    return ''.join(token.value for token in self.flatten())\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 165, in <genexpr>\n    return ''.join(token.value for token in self.flatten())\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 214, in flatten\n    yield from token.flatten()\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 214, in flatten\n    yield from token.flatten()\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 214, in flatten\n    yield from token.flatten()\n  [Previous line repeated 983 more times]\nRecursionError: maximum recursion depth exceeded\n```\n\n### Fix suggestion\nThe [flatten()](https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/sql.py#L207) function of TokenList class should limit the recursion to a maximal depth:\n```py\nfrom sqlparse.exceptions import SQLParseError\n\nMAX_DEPTH = 100\n\n    def flatten(self, depth=1):\n        \"\"\"Generator yielding ungrouped tokens.\n\n        This method is recursively called for all child tokens.\n        \"\"\"\n    if depth >= MAX_DEPTH:\n        raise SQLParseError('Maximal depth reached')\n        for token in self.tokens:\n            if token.is_group:\n                yield from token.flatten(depth + 1)\n            else:\n                yield token\n```\n\n### Impact\nDenial of Service (the impact depends on the use).\nAnyone parsing a user input with sqlparse.parse() is affected.\n",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "sqlparse",
              "purl": "pkg:pypi/sqlparse"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "0.5.0"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.0",
              "0.1.1",
              "0.1.10",
              "0.1.11",
              "0.1.12",
              "0.1.13",
              "0.1.14",
              "0.1.15",
              "0.1.16",
              "0.1.17",
              "0.1.18",
              "0.1.19",
              "0.1.2",
              "0.1.3",
              "0.1.4",
              "0.1.5",
              "0.1.6",
              "0.1.7",
              "0.1.8",
              "0.1.9",
              "0.2.0",
              "0.2.1",
              "0.2.2",
              "0.2.3",
              "0.2.4",
              "0.3.0",
              "0.3.1",
              "0.4.0",
              "0.4.1",
              "0.4.2",
              "0.4.3",
              "0.4.4"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/04/GHSA-2m57-hf25-phgg/GHSA-2m57-hf25-phgg.json"
            },
            "ecosystem_specific": {
              "affected_functions": [
                "sqlparse.parse"
              ]
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/andialbrecht/sqlparse/security/advisories/GHSA-2m57-hf25-phgg"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-4340"
          },
          {
            "type": "WEB",
            "url": "https://github.com/andialbrecht/sqlparse/commit/b4a39d9850969b4e1d6940d32094ee0b42a2cf03"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/andialbrecht/sqlparse"
          },
          {
            "type": "WEB",
            "url": "https://research.jfrog.com/vulnerabilities/sqlparse-stack-exhaustion-dos-jfsa-2024-001031292"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-674"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2024-04-15T20:21:25Z",
          "nvd_published_at": null,
          "severity": "HIGH"
        }
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-2m57-hf25-phgg"
        ],
        "aliases": [
          "CVE-2024-4340",
          "GHSA-2m57-hf25-phgg"
        ],
        "max_severity": "7.5"
      }
    ]
  }
]